"""Generated base schema

Revision ID: 352241199e9
Revises: 
Create Date: 2015-07-31 11:39:30.937118

"""

# revision identifiers, used by Alembic.
revision = '352241199e9'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'text'),
    sa.UniqueConstraint('id')
    )
    op.create_table('questionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('questionary_id', sa.Integer(), nullable=True),
    sa.Column('valid_answer', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['questionary_id'], ['questionary.id'], ),
    sa.ForeignKeyConstraint(['valid_answer'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_answers')
    op.drop_table('question')
    op.drop_table('questionary')
    op.drop_table('answer')
    ### end Alembic commands ###
