"""Added field to questionary

Revision ID: 56b885c627f2
Revises: 352241199e9
Create Date: 2015-07-31 13:59:28.331264

"""

# revision identifiers, used by Alembic.
revision = '56b885c627f2'
down_revision = '352241199e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'question', ['id'])
    op.create_unique_constraint(None, 'question_answers', ['id'])
    op.add_column('questionary', sa.Column('todotest_link', sa.String(length=2048), nullable=True))
    op.add_column('questionary', sa.Column('type', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'questionary', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionary', type_='unique')
    op.drop_column('questionary', 'type')
    op.drop_column('questionary', 'todotest_link')
    op.drop_constraint(None, 'question_answers', type_='unique')
    op.drop_constraint(None, 'question', type_='unique')
    ### end Alembic commands ###
